import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import LoginForm from '../components/LoginForm'
import RegisterForm from '../components/RegisterForm'
import Vault from '../components/Vault'
import styles from '../styles/Home.module.css'
import { VaultItem } from '../types/VaultItem'

const Home: NextPage = () => {
  const [step, setStep]=useState<"login"|"register"|"vault">("login");
  const [vault, setVault]=useState<VaultItem[]>([]);
  const [vaultKey, setVaultKey]=useState("");

  useEffect(() =>{
    const vaultFromStorage=window.sessionStorage.getItem("vault");
    const vaultKeyFromStorage=window.sessionStorage.getItem("vaultKey");
    if(vaultFromStorage){
      setVault(JSON.parse(vaultFromStorage));
    }
    if(vaultKeyFromStorage){
      setVaultKey(vaultKeyFromStorage);
      setStep("vault");
    }

  },[]);

  return (
    <div className={styles.container}>
        <Head>
          <title>Password Manager App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
           {step === "register" && (
          <RegisterForm setStep={setStep} setVaultKey={setVaultKey} />
        )}
        {step === "login" && (
          <LoginForm
            setVault={setVault}
            setStep={setStep}
            setVaultKey={setVaultKey}
          />
        )}
        {step === "vault" && <Vault vault={vault} vaultKey={vaultKey} />}
        </main>
    </div>
  )
}

export default Home
